env:
  es6: true
  jest: true

extends:
  - prettier
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: [.ts', '.d.ts']
